[project]
docs_dir = "."
nav = [
  { "Home" = "index.md" },
  { "Photonic FDTD" = [
    { "MMI Quickstart" = "nbs/fdtd_mmi_gpdk.md" },
    { "Directional Coupler" = "nbs/fdtd_directional_coupler.md" },
    { "Waveguide Crossing" = "nbs/fdtd_waveguide_crossing.md" },
    { "Broadband Directional Coupler" = "nbs/fdtd_broadband_directional_coupler.md" },
    { "Meep: Directional Coupler" = "nbs/meep_dc.md" },
    { "Meep: 2D Directional Coupler" = "nbs/meep_2d.md" },
    { "Meep: 2D Grating Coupler" = "nbs/meep_2d_xz_gc.md" },
    { "Meep: 2D Grating Coupler Sweep" = "nbs/meep_2d_xz_gc_wavelength_sweep.md" },
    { "Meep: 3D MMI Comparison" = "nbs/meep_ybranch.md" }
  ] },
  { "FEM for RF" = [
    { "CPW (Lumped Ports)" = "nbs/palace_cpw_lumped.md" },
    { "Microstrip" = "nbs/palace_microstrip.md" },
    { "Branch Line Coupler" = "nbs/palace_branch_line_coupler.md" },
    { "Parallel Simulations: Width Sweep" = "nbs/palace_width_sweep.md" },
    { "QPDK Resonator" = "nbs/palace_qpdk_resonator.md" },
    { "Inductor" = "nbs/palace_inductor.md" },
    { "CPW Via Transition" = "nbs/palace_cpw_via.md" },
    { "Field Visualization" = "nbs/palace_cpw_fields.md" }
  ] },
  { "Changelog" = "CHANGELOG.md" },
  { "API Reference" = [
    { "GDSFactory FDTD" = "api/fdtd.md" },
    { "Palace" = "api/palace.md" },
    { "Meep" = "api/meep.md" },
    { "Common" = "api/common.md" },
    { "Cloud" = "api/cloud.md" }
  ] }
]
site_dir = "site"
site_name = "gsim"
site_url = "https://gdsfactory.com/gsim"
repo_url = "https://gdsfactory.com/"
repo_name = "gdsfactory.com"
copyright = "Copyright &copy; 2025 GDSFactory"

[project.plugins.search]

[project.plugins.mkdocstrings.handlers.python]
paths = ["../src"]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://pandas.pydata.org/docs/objects.inv"
]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_options = { ignore_init_summary = true }
docstring_section_style = "list"
docstring_style = "google"
filters = ["!^_"]
heading_level = 1
inherited_members = true
line_length = 88
merge_init_into_class = true
separate_signature = true
show_root_full_path = false
show_root_heading = true
show_signature_annotations = true
show_source = true
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
summary = true

[project.theme]
name = "material"
custom_dir = "overrides"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"

[project.theme.palette.toggle]
icon = "material/brightness-7"
name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"

[project.theme.palette.toggle]
icon = "material/brightness-4"
name = "Switch to light mode"
